---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: bbox-cephfs
    apps.open-cluster-management.io/github-path: busybox-cephfs
  name: busybox-sub
spec:
    channel: ramen-samples/ramen-gitops
    placement:
      placementRef:
        kind: Placement
        name: busybox-placement
