kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: groups-storage
  labels:
    placement: groups-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
