apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: groups
  name: groups
spec:
  replicas: 1
  selector:
    matchLabels:
      name: groups
  template:
    metadata:
      labels:
        name: groups
    spec:
      containers:
      - image: quay.io/shyamsundarr/groups:canary
        name: groups
        ports:
        - name: groups
          containerPort: 27017
        volumeMounts:
          - name: groups-vol
            mountPath: /bitnami
      volumes:
        - name: groups-vol
          persistentVolumeClaim:
            claimName: groups-storage
