---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-1
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
