---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-1
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "rook-ceph-block"
  resources:
    requests:
      storage: 1Gi
