---
resources:
  - ../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-cephfs
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany
