---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      appname: busybox
  serviceName: "busybox"
  replicas: 3
  template:
    metadata:
      labels:
        appname: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'while true; do echo $(date) | tee -a /mnt/test/outfile; sync; sleep 10; done']
        volumeMounts:
        - name: busybox-pvc
          mountPath: /mnt/test
  volumeClaimTemplates:
  - metadata:
      name: busybox-pvc
      labels:
        appname: busybox
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 1Gi
